# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# Variables that are specific to tenant deployments, such as packages, proxies, etc
---
tenant: iag-ProdA
proxy_env:
  http_proxy: "http://proxy.auiag.corp:8080"
  https_proxy: "http://proxy.auiag.corp:8080"
  proxy_username: "sys_sde_apps"
  proxy_password: "Sw%40nLake9"
